name: helloWorld

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : Run one-line script
      run: echo "Hello World!"
    - name: Run multi-line script
      run: |
        echo "Hello World, Welcome to multi-line run script!"
        echo date
