name: Sample_MultiJobs
on:
  push:
    branches: [main]
env:
  ARTIFACT_NAME: "TestArtifact"
  
jobs:
  job1:
    name: job1
    runs-on: windows-latest
    steps:
    - name: Run sample print command
      run: echo "This is job1, step1 %DATE%"
    - name: Checkout code
      uses: actions/checkout@v2

  job3:
    name: job3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Assuming you might need to checkout before handling files
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}_${{ github.run_id }} 
        path: . # Add specific paths you wish to upload if needed

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: [job1, job3]
    steps:
      - name: Simple Print
        run: echo "This is job2, step1"
